const forecast = {
    data: {
        location: {
          name: "Sunol",
          region: "California",
          country: "USA",
          lat: 37.6,
          lon: -121.89,
          tz_id: "America/Los_Angeles",
          localtime_epoch: 1711089720,
          localtime: "2024-03-21 23:42",
        },
        current: {
          last_updated_epoch: 1711089000,
          last_updated: "2024-03-21 23:30",
          temp_c: 12.2,
          temp_f: 54,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 300,
          wind_dir: "WNW",
          pressure_mb: 1019,
          pressure_in: 30.09,
          precip_mm: 0,
          precip_in: 0,
          humidity: 77,
          cloud: 0,
          feelslike_c: 12.5,
          feelslike_f: 54.4,
          vis_km: 16,
          vis_miles: 9,
          uv: 1,
          gust_mph: 5.2,
          gust_kph: 8.4,
        },
        forecast: {
          forecastday: [
            {
              date: "2024-03-21",
              date_epoch: 1710979200,
              day: {
                maxtemp_c: 18.4,
                maxtemp_f: 65.2,
                mintemp_c: 6.8,
                mintemp_f: 44.2,
                avgtemp_c: 12.2,
                avgtemp_f: 54,
                maxwind_mph: 7.6,
                maxwind_kph: 12.2,
                totalprecip_mm: 0,
                totalprecip_in: 0,
                totalsnow_cm: 0,
                avgvis_km: 10,
                avgvis_miles: 6,
                avghumidity: 75,
                daily_will_it_rain: 0,
                daily_chance_of_rain: 0,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Partly Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                  code: 1003,
                },
                uv: 5,
              },
              astro: {
                sunrise: "07:09 AM",
                sunset: "07:21 PM",
                moonrise: "04:13 PM",
                moonset: "05:47 AM",
                moon_phase: "Waxing Gibbous",
                moon_illumination: 84,
                is_moon_up: 1,
                is_sun_up: 1,
              },
              hour: [
                {
                  time_epoch: 1711004400,
                  time: "2024-03-21 00:00",
                  temp_c: 7.3,
                  temp_f: 45.1,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 3.4,
                  wind_kph: 5.4,
                  wind_degree: 227,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 84,
                  cloud: 5,
                  feelslike_c: 6.6,
                  feelslike_f: 43.8,
                  windchill_c: 6.6,
                  windchill_f: 43.8,
                  heatindex_c: 7.3,
                  heatindex_f: 45.1,
                  dewpoint_c: 4.6,
                  dewpoint_f: 40.3,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 7,
                  gust_kph: 11.3,
                  uv: 1,
                },
                {
                  time_epoch: 1711008000,
                  time: "2024-03-21 01:00",
                  temp_c: 7.1,
                  temp_f: 44.7,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 3.1,
                  wind_kph: 5,
                  wind_degree: 220,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 85,
                  cloud: 4,
                  feelslike_c: 6.3,
                  feelslike_f: 43.4,
                  windchill_c: 6.3,
                  windchill_f: 43.4,
                  heatindex_c: 7.1,
                  heatindex_f: 44.7,
                  dewpoint_c: 4.4,
                  dewpoint_f: 39.9,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 6.6,
                  gust_kph: 10.6,
                  uv: 1,
                },
                {
                  time_epoch: 1711011600,
                  time: "2024-03-21 02:00",
                  temp_c: 7,
                  temp_f: 44.7,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 3.1,
                  wind_kph: 5,
                  wind_degree: 228,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 87,
                  cloud: 4,
                  feelslike_c: 6.5,
                  feelslike_f: 43.7,
                  windchill_c: 6.5,
                  windchill_f: 43.7,
                  heatindex_c: 7.1,
                  heatindex_f: 44.7,
                  dewpoint_c: 4.8,
                  dewpoint_f: 40.6,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 6.6,
                  gust_kph: 10.6,
                  uv: 1,
                },
                {
                  time_epoch: 1711015200,
                  time: "2024-03-21 03:00",
                  temp_c: 7,
                  temp_f: 44.7,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 2.7,
                  wind_kph: 4.3,
                  wind_degree: 220,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 88,
                  cloud: 2,
                  feelslike_c: 6.7,
                  feelslike_f: 44,
                  windchill_c: 6.7,
                  windchill_f: 44,
                  heatindex_c: 7.1,
                  heatindex_f: 44.7,
                  dewpoint_c: 5.2,
                  dewpoint_f: 41.3,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 5.6,
                  gust_kph: 9.1,
                  uv: 1,
                },
                {
                  time_epoch: 1711018800,
                  time: "2024-03-21 04:00",
                  temp_c: 7.1,
                  temp_f: 44.8,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 2.5,
                  wind_kph: 4,
                  wind_degree: 237,
                  wind_dir: "WSW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 90,
                  cloud: 15,
                  feelslike_c: 7,
                  feelslike_f: 44.5,
                  windchill_c: 7,
                  windchill_f: 44.5,
                  heatindex_c: 7.1,
                  heatindex_f: 44.8,
                  dewpoint_c: 5.5,
                  dewpoint_f: 41.9,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 5.2,
                  gust_kph: 8.3,
                  uv: 1,
                },
                {
                  time_epoch: 1711022400,
                  time: "2024-03-21 05:00",
                  temp_c: 7.4,
                  temp_f: 45.2,
                  is_day: 0,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    code: 1003,
                  },
                  wind_mph: 2,
                  wind_kph: 3.2,
                  wind_degree: 222,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 92,
                  cloud: 31,
                  feelslike_c: 7.4,
                  feelslike_f: 45.3,
                  windchill_c: 7.4,
                  windchill_f: 45.3,
                  heatindex_c: 7.4,
                  heatindex_f: 45.2,
                  dewpoint_c: 6,
                  dewpoint_f: 42.7,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 4.2,
                  gust_kph: 6.8,
                  uv: 1,
                },
                {
                  time_epoch: 1711026000,
                  time: "2024-03-21 06:00",
                  temp_c: 8,
                  temp_f: 46.3,
                  is_day: 0,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    code: 1003,
                  },
                  wind_mph: 2,
                  wind_kph: 3.2,
                  wind_degree: 223,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 93,
                  cloud: 46,
                  feelslike_c: 8,
                  feelslike_f: 46.3,
                  windchill_c: 8,
                  windchill_f: 46.3,
                  heatindex_c: 8,
                  heatindex_f: 46.3,
                  dewpoint_c: 6.6,
                  dewpoint_f: 43.8,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 4.2,
                  gust_kph: 6.8,
                  uv: 1,
                },
                {
                  time_epoch: 1711029600,
                  time: "2024-03-21 07:00",
                  temp_c: 9.3,
                  temp_f: 48.7,
                  is_day: 0,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    code: 1003,
                  },
                  wind_mph: 1.6,
                  wind_kph: 2.5,
                  wind_degree: 227,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.12,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 94,
                  cloud: 53,
                  feelslike_c: 9.5,
                  feelslike_f: 49.1,
                  windchill_c: 9.5,
                  windchill_f: 49.1,
                  heatindex_c: 9.3,
                  heatindex_f: 48.7,
                  dewpoint_c: 7.6,
                  dewpoint_f: 45.7,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 3,
                  gust_kph: 4.8,
                  uv: 1,
                },
                {
                  time_epoch: 1711033200,
                  time: "2024-03-21 08:00",
                  temp_c: 11.1,
                  temp_f: 51.9,
                  is_day: 1,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    code: 1003,
                  },
                  wind_mph: 2,
                  wind_kph: 3.2,
                  wind_degree: 189,
                  wind_dir: "S",
                  pressure_mb: 1020,
                  pressure_in: 30.13,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 90,
                  cloud: 33,
                  feelslike_c: 11.4,
                  feelslike_f: 52.5,
                  windchill_c: 11.4,
                  windchill_f: 52.5,
                  heatindex_c: 11.1,
                  heatindex_f: 51.9,
                  dewpoint_c: 8.9,
                  dewpoint_f: 48,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 3.1,
                  gust_kph: 4.9,
                  uv: 4,
                },
                {
                  time_epoch: 1711036800,
                  time: "2024-03-21 09:00",
                  temp_c: 12.9,
                  temp_f: 55.3,
                  is_day: 1,
                  condition: {
                    text: "Sunny",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    code: 1000,
                  },
                  wind_mph: 2.5,
                  wind_kph: 4,
                  wind_degree: 222,
                  wind_dir: "SW",
                  pressure_mb: 1020,
                  pressure_in: 30.13,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 81,
                  cloud: 10,
                  feelslike_c: 13.1,
                  feelslike_f: 55.6,
                  windchill_c: 13.1,
                  windchill_f: 55.6,
                  heatindex_c: 12.9,
                  heatindex_f: 55.3,
                  dewpoint_c: 9.8,
                  dewpoint_f: 49.6,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 2.8,
                  gust_kph: 4.6,
                  uv: 4,
                },
                {
                  time_epoch: 1711040400,
                  time: "2024-03-21 10:00",
                  temp_c: 14.6,
                  temp_f: 58.3,
                  is_day: 1,
                  condition: {
                    text: "Sunny",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    code: 1000,
                  },
                  wind_mph: 4.3,
                  wind_kph: 6.8,
                  wind_degree: 260,
                  wind_dir: "W",
                  pressure_mb: 1021,
                  pressure_in: 30.14,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 72,
                  cloud: 21,
                  feelslike_c: 14.7,
                  feelslike_f: 58.5,
                  windchill_c: 14.7,
                  windchill_f: 58.5,
                  heatindex_c: 14.6,
                  heatindex_f: 58.3,
                  dewpoint_c: 9.9,
                  dewpoint_f: 49.7,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 4.9,
                  gust_kph: 7.9,
                  uv: 4,
                },
                {
                  time_epoch: 1711044000,
                  time: "2024-03-21 11:00",
                  temp_c: 16,
                  temp_f: 60.8,
                  is_day: 1,
                  condition: {
                    text: "Sunny",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    code: 1000,
                  },
                  wind_mph: 4.5,
                  wind_kph: 7.2,
                  wind_degree: 254,
                  wind_dir: "WSW",
                  pressure_mb: 1021,
                  pressure_in: 30.14,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 66,
                  cloud: 16,
                  feelslike_c: 16.1,
                  feelslike_f: 60.9,
                  windchill_c: 16.1,
                  windchill_f: 60.9,
                  heatindex_c: 16,
                  heatindex_f: 60.8,
                  dewpoint_c: 9.9,
                  dewpoint_f: 49.7,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 5.1,
                  gust_kph: 8.3,
                  uv: 5,
                },
                {
                  time_epoch: 1711047600,
                  time: "2024-03-21 12:00",
                  temp_c: 17.1,
                  temp_f: 62.9,
                  is_day: 1,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    code: 1003,
                  },
                  wind_mph: 5.1,
                  wind_kph: 8.3,
                  wind_degree: 259,
                  wind_dir: "W",
                  pressure_mb: 1020,
                  pressure_in: 30.13,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 61,
                  cloud: 30,
                  feelslike_c: 17.2,
                  feelslike_f: 62.9,
                  windchill_c: 17.2,
                  windchill_f: 62.9,
                  heatindex_c: 17.1,
                  heatindex_f: 62.9,
                  dewpoint_c: 9.7,
                  dewpoint_f: 49.5,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 5.9,
                  gust_kph: 9.5,
                  uv: 5,
                },
                {
                  time_epoch: 1711051200,
                  time: "2024-03-21 13:00",
                  temp_c: 17.8,
                  temp_f: 64,
                  is_day: 1,
                  condition: {
                    text: "Overcast ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    code: 1009,
                  },
                  wind_mph: 5.8,
                  wind_kph: 9.4,
                  wind_degree: 262,
                  wind_dir: "W",
                  pressure_mb: 1020,
                  pressure_in: 30.12,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 56,
                  cloud: 100,
                  feelslike_c: 17.8,
                  feelslike_f: 64,
                  windchill_c: 17.8,
                  windchill_f: 64,
                  heatindex_c: 17.8,
                  heatindex_f: 64,
                  dewpoint_c: 9.5,
                  dewpoint_f: 49,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 6.7,
                  gust_kph: 10.8,
                  uv: 4,
                },
                {
                  time_epoch: 1711054800,
                  time: "2024-03-21 14:00",
                  temp_c: 18,
                  temp_f: 64.3,
                  is_day: 1,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    code: 1003,
                  },
                  wind_mph: 7.2,
                  wind_kph: 11.5,
                  wind_degree: 268,
                  wind_dir: "W",
                  pressure_mb: 1020,
                  pressure_in: 30.12,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 54,
                  cloud: 54,
                  feelslike_c: 18,
                  feelslike_f: 64.4,
                  windchill_c: 18,
                  windchill_f: 64.4,
                  heatindex_c: 18,
                  heatindex_f: 64.3,
                  dewpoint_c: 9.1,
                  dewpoint_f: 48.3,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 8.2,
                  gust_kph: 13.2,
                  uv: 5,
                },
                {
                  time_epoch: 1711058400,
                  time: "2024-03-21 15:00",
                  temp_c: 17.9,
                  temp_f: 64.2,
                  is_day: 1,
                  condition: {
                    text: "Overcast ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    code: 1009,
                  },
                  wind_mph: 6.9,
                  wind_kph: 11.2,
                  wind_degree: 273,
                  wind_dir: "W",
                  pressure_mb: 1019,
                  pressure_in: 30.1,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 52,
                  cloud: 91,
                  feelslike_c: 17.9,
                  feelslike_f: 64.2,
                  windchill_c: 17.9,
                  windchill_f: 64.2,
                  heatindex_c: 17.9,
                  heatindex_f: 64.2,
                  dewpoint_c: 8.2,
                  dewpoint_f: 46.8,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 8,
                  gust_kph: 12.9,
                  uv: 4,
                },
                {
                  time_epoch: 1711062000,
                  time: "2024-03-21 16:00",
                  temp_c: 17.4,
                  temp_f: 63.3,
                  is_day: 1,
                  condition: {
                    text: "Partly Cloudy ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    code: 1003,
                  },
                  wind_mph: 7.4,
                  wind_kph: 11.9,
                  wind_degree: 278,
                  wind_dir: "W",
                  pressure_mb: 1019,
                  pressure_in: 30.08,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 52,
                  cloud: 62,
                  feelslike_c: 17.4,
                  feelslike_f: 63.3,
                  windchill_c: 17.4,
                  windchill_f: 63.3,
                  heatindex_c: 17.4,
                  heatindex_f: 63.3,
                  dewpoint_c: 7.9,
                  dewpoint_f: 46.3,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 8.5,
                  gust_kph: 13.7,
                  uv: 5,
                },
                {
                  time_epoch: 1711065600,
                  time: "2024-03-21 17:00",
                  temp_c: 16.1,
                  temp_f: 61,
                  is_day: 1,
                  condition: {
                    text: "Overcast ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    code: 1009,
                  },
                  wind_mph: 7.6,
                  wind_kph: 12.2,
                  wind_degree: 282,
                  wind_dir: "WNW",
                  pressure_mb: 1018,
                  pressure_in: 30.08,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 54,
                  cloud: 98,
                  feelslike_c: 16,
                  feelslike_f: 60.7,
                  windchill_c: 16,
                  windchill_f: 60.7,
                  heatindex_c: 16.1,
                  heatindex_f: 61,
                  dewpoint_c: 7.6,
                  dewpoint_f: 45.8,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 9.5,
                  gust_kph: 15.2,
                  uv: 4,
                },
                {
                  time_epoch: 1711069200,
                  time: "2024-03-21 18:00",
                  temp_c: 14.6,
                  temp_f: 58.3,
                  is_day: 1,
                  condition: {
                    text: "Overcast ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    code: 1009,
                  },
                  wind_mph: 5.4,
                  wind_kph: 8.6,
                  wind_degree: 285,
                  wind_dir: "WNW",
                  pressure_mb: 1018,
                  pressure_in: 30.08,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 63,
                  cloud: 100,
                  feelslike_c: 14.5,
                  feelslike_f: 58.1,
                  windchill_c: 14.5,
                  windchill_f: 58.1,
                  heatindex_c: 14.6,
                  heatindex_f: 58.3,
                  dewpoint_c: 7.8,
                  dewpoint_f: 46.1,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 8.3,
                  gust_kph: 13.3,
                  uv: 3,
                },
                {
                  time_epoch: 1711072800,
                  time: "2024-03-21 19:00",
                  temp_c: 13.4,
                  temp_f: 56.1,
                  is_day: 1,
                  condition: {
                    text: "Overcast ",
                    icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    code: 1009,
                  },
                  wind_mph: 3.8,
                  wind_kph: 6.1,
                  wind_degree: 279,
                  wind_dir: "W",
                  pressure_mb: 1019,
                  pressure_in: 30.09,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 73,
                  cloud: 100,
                  feelslike_c: 13.6,
                  feelslike_f: 56.4,
                  windchill_c: 13.6,
                  windchill_f: 56.4,
                  heatindex_c: 13.4,
                  heatindex_f: 56.1,
                  dewpoint_c: 8.3,
                  dewpoint_f: 47,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 6.6,
                  gust_kph: 10.7,
                  uv: 3,
                },
                {
                  time_epoch: 1711076400,
                  time: "2024-03-21 20:00",
                  temp_c: 12.4,
                  temp_f: 54.4,
                  is_day: 0,
                  condition: {
                    text: "Overcast ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    code: 1009,
                  },
                  wind_mph: 2.2,
                  wind_kph: 3.6,
                  wind_degree: 260,
                  wind_dir: "W",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 77,
                  cloud: 100,
                  feelslike_c: 12.7,
                  feelslike_f: 54.8,
                  windchill_c: 12.7,
                  windchill_f: 54.8,
                  heatindex_c: 12.4,
                  heatindex_f: 54.4,
                  dewpoint_c: 8.3,
                  dewpoint_f: 46.9,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 4,
                  gust_kph: 6.4,
                  uv: 1,
                },
                {
                  time_epoch: 1711080000,
                  time: "2024-03-21 21:00",
                  temp_c: 11.8,
                  temp_f: 53.2,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 2.5,
                  wind_kph: 4,
                  wind_degree: 247,
                  wind_dir: "WSW",
                  pressure_mb: 1020,
                  pressure_in: 30.12,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 81,
                  cloud: 10,
                  feelslike_c: 12.1,
                  feelslike_f: 53.8,
                  windchill_c: 12.1,
                  windchill_f: 53.8,
                  heatindex_c: 11.8,
                  heatindex_f: 53.2,
                  dewpoint_c: 8.3,
                  dewpoint_f: 46.9,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 4.5,
                  gust_kph: 7.3,
                  uv: 1,
                },
                {
                  time_epoch: 1711083600,
                  time: "2024-03-21 22:00",
                  temp_c: 11.2,
                  temp_f: 52.2,
                  is_day: 0,
                  condition: {
                    text: "Clear ",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 2,
                  wind_kph: 3.2,
                  wind_degree: 213,
                  wind_dir: "SSW",
                  pressure_mb: 1020,
                  pressure_in: 30.11,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 83,
                  cloud: 6,
                  feelslike_c: 11.4,
                  feelslike_f: 52.5,
                  windchill_c: 11.4,
                  windchill_f: 52.5,
                  heatindex_c: 11.2,
                  heatindex_f: 52.2,
                  dewpoint_c: 8.3,
                  dewpoint_f: 46.9,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 10,
                  vis_miles: 6,
                  gust_mph: 3.8,
                  gust_kph: 6,
                  uv: 1,
                },
                {
                  time_epoch: 1711087200,
                  time: "2024-03-21 23:00",
                  temp_c: 12.2,
                  temp_f: 54,
                  is_day: 0,
                  condition: {
                    text: "Clear",
                    icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    code: 1000,
                  },
                  wind_mph: 3.8,
                  wind_kph: 6.1,
                  wind_degree: 300,
                  wind_dir: "WNW",
                  pressure_mb: 1019,
                  pressure_in: 30.09,
                  precip_mm: 0,
                  precip_in: 0,
                  snow_cm: 0,
                  humidity: 77,
                  cloud: 0,
                  feelslike_c: 11,
                  feelslike_f: 51.8,
                  windchill_c: 11,
                  windchill_f: 51.8,
                  heatindex_c: 10.8,
                  heatindex_f: 51.4,
                  dewpoint_c: 8.2,
                  dewpoint_f: 46.7,
                  will_it_rain: 0,
                  chance_of_rain: 0,
                  will_it_snow: 0,
                  chance_of_snow: 0,
                  vis_km: 16,
                  vis_miles: 9,
                  gust_mph: 5.2,
                  gust_kph: 8.4,
                  uv: 1,
                },
              ],
            },
          ],
        },
    }
}
const currentWeather = {
  data: 
    {"location":{"name":"San Ramon","region":"California","country":"USA","lat":37.75,"lon":-121.95,"tz_id":"America/Los_Angeles","localtime_epoch":1711565826,"localtime":"2024-03-27 11:57"},"current":{"last_updated_epoch":1711565100,"last_updated":"2024-03-27 11:45","temp_c":13.9,"temp_f":57.0,"is_day":1,"condition":{"text":"Light rain","icon":"//cdn.weatherapi.com/weather/64x64/day/296.png","code":1183},"wind_mph":12.5,"wind_kph":20.2,"wind_degree":180,"wind_dir":"S","pressure_mb":1021.0,"pressure_in":30.15,"precip_mm":0.0,"precip_in":0.0,"humidity":64,"cloud":100,"feelslike_c":13.7,"feelslike_f":56.6,"vis_km":16.0,"vis_miles":9.0,"uv":4.0,"gust_mph":17.0,"gust_kph":27.4}}
}
module.exports = {forecast, currentWeather}